# Generated by Django 4.2.7 on 2024-07-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='cart_image',
        ),
    ]
